export const STATE_CASHER =  'NOT_PAID'
export const STATE_SAMPLER =  'WAITING_TAKEN_SAMPLE,NOT_ENOUGH_SAMPLE'
export const STATE_TECHNICIAN = 'TAKEN_SAMPLE,ENOUGH_SAMPLE,RETURN_RESULT'
export const STATE_COMPLETED =  'RETURN_RESULT,COMPLETED'
